name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [header, footer, root-app]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependecnies for ${{ matrix.app }}
        run: |
          cd ${{ matrix.app }}
          yarn install

      - name: Run tests for ${{ matrix.app }}
        run: |
          cd ${{ matrix.app }}
          yarn build
