name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Clean Yarn cache
        run: yarn cache clean

      - name: Install dependencies for each app
        run: |
          yarn install:all

      - name: Start apps
        run: |
          yarn start:header
          yarn start:footer
          yarn start:root-app
        env:
          CI: true

      - name: Run Cypress E2E Tests
        run: |
          yarn --cwd root-app test:e2e
